#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PhoneApp.Resource", IsApplication=true)]

namespace PhoneApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public const int AMARILLO = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int BLANCO = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int CELESTE = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int COBALTO = 2130968587;
			
			// aapt resource value: 0x7f040002
			public const int MORADO = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int NARANJA = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int NEGRO = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int PISTACHO = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int ROJO = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int ROSA = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int SALMON = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int VVIVO = 2130968584;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int CallButton = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int CallHistoryButton = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int PhoneNumberText = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int TranslateButton = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int ValidaFirstButton = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int miMensajeText = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int miMensajeText2 = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int textEmailAddress = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int textPassword = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int textView2 = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int validarCredButton = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Validatorjc = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int CallHistory = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int ValidatorJC = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
